### ISSUE TITLE
ADB TCP connection connected but device offline and not accessible

### ISSUE THREAD

**Issue by cosote** [leapdroid-team/leapdroid#19]
ADB TCP connection is far better and more stable than using device name connection type.
Ports and emulator name can be changed with "C:\Program Files\Leapdroid\VM\vboxmanage" guestproperty set vm1 adb_port 5557, and multiple instances can be managed, but only using its "emulator-5556" device name. The digits of emulator-5556 are derived from configured adb_port - 1, but connections cannot always be established that way. Different emulator restarts are required including restarting adb server. Please add TCP support to LeapDroid, that would solve this problem.

**Comment by huisinro** [comment]
yes, we are aware of this TCP approach. However, currently since we use NAT as primary network method, the v doesn't have a real ip address that host can easily connect, so it will involve NAT port forwarding, inconvenient and error prone. Once we add bridged network, we will support tcp mode. You will be able to setprop to switch to tcp mode.
